### ISSUE TITLE
Very slow rebuild time on development

### ISSUE THREAD

**Issue by sigo** [DaleLJefferson/gatsby-plugin-typescript-checker#1]
Hello.

Thanks for your work! It is great. However I noticed that using `gatsby-plugin-typescript-checker` increases about 10 times rebuilt time.

Default starter rebuild at 200-300ms, but this same code with plugin rebuild 2.5-3s.

Is this known?

**Comment by smockle** [comment]
I have the same issue: With `"gatsby-plugin-typescript-checker"` enabled in `gatsby-config.json`, rebuilds take ~4956ms. When I comment it out, rebuilds take ~299ms.

```
"gatsby": "2.3.31",
"gatsby-plugin-typescript": "2.0.13",
"gatsby-plugin-typescript-checker": "1.0.3",
"react": "16.8.6",
"typescript": "3.4.5"
```

**Comment by sigo** [comment]
@smockle try use this tsconfig:

```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "lib": ["dom", "es2017"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext"
  }
}
```

If i remember correctly, setting `skipLibCheck` to `true` keeps rebuilding time actually at the same level as pure js. However, in my opinion, typescript manual lack more description for this option. It says only:

> skipLibCheck - Skip type checking of all declaration files (*.d.ts).

Others settings in pasted code probably aren't related to time rebuilding.

I've used this config in next app and I get it from https://github.com/zeit/next-plugins/tree/master/packages/next-typescript.

**Summary: I think is is not gatsby issue itself.**

**Comment by smockle** [comment]
> If i remember correctly, setting `skipLibCheck` to `true` keeps rebuilding time actually at the same level as pure js.

Thanks for the suggestion!

In my project:
* With `skipLibCheck: false`, rebuilds take ~`5879ms` 
* With `skipLibCheck: true`, rebuilds take ~`1130ms`
* Without `gatsby-plugin-typescript-checker`, rebuilds take ~`378ms`

`fork-ts-checker-webpack-plugin` should run in a separate process, so I don’t understand why there is any impact on build (or hot-module-reload) times. 🤔
