### ISSUE TITLE
Breaks url-loader for images

### ISSUE THREAD

**Issue by abeMedia** [DaleLJefferson/gatsby-plugin-typescript-checker#4]
If I enable this plugin importing images as described on https://www.gatsbyjs.org/docs/importing-assets-into-files/ no longer works.

Instead I get an error message saying something along the lines of `Cannot find module './logo.png'.`

**Comment by mpern** [comment]
You have to tell typescript to allow import of `*.png` files in a module declaration, e.g.

`src/declarations.d.ts`

```
declare module "*.png";
```
https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations

**Comment by abeMedia** [comment]
Thanks for responding. I did realise shortly after posting this but forgot to close the ticket...
